"""
Django settings for inventory_system project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from decouple import config
import os
from pathlib import Path
import logging


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', "e270-102-91-104-49.ngrok-free.app", ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'corsheaders',
    'django_crontab',

    # Local apps
    'core',
    'web',
]

# Cron job definitions
CRONJOBS = [
    # Sync FROM Airtable TO Django every 15 minutes
    ('*/15 * * * *', 'core.management.commands.sync_from_airtable.Command', '--quiet'),
    
    # Alternative schedules (uncomment what you prefer):
    # Every 5 minutes: ('*/5 * * * *', 'core.management.commands.sync_from_airtable.Command', '--quiet'),
    # Every 30 minutes: ('*/30 * * * *', 'core.management.commands.sync_from_airtable.Command', '--quiet'),
    # Every hour: ('0 * * * *', 'core.management.commands.sync_from_airtable.Command', '--quiet'),
    
    # Sync only inventory every 10 minutes
    ('*/10 * * * *', 'core.management.commands.sync_from_airtable.Command', '--type=inventory --quiet'),
]

# Cron job settings
CRONTAB_DJANGO_SETTINGS_MODULE = 'inventory_system.settings'
CRONTAB_COMMAND_PREFIX = f'cd {BASE_DIR} &&'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'inventory_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'inventory_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Path configuration for your existing data
CLEAN_DATA_PATH = os.path.join(BASE_DIR, config('CLEAN_DATA_PATH', default='../clean_data'))
RAW_REPORTS_PATH = os.path.join(BASE_DIR, config('RAW_REPORTS_PATH', default='../raw_daily_reports'))
SKU_MAPPER_PATH = os.path.join(BASE_DIR, config('SKU_MAPPER_PATH', default='../sku_mapper'))

# Baserow API configuration
BASEROW_BASE_URL = 'https://api.baserow.io'
BASEROW_API_TOKEN = config('BASEROW_API_TOKEN')
BASEROW_DATABASE_ID = config('BASEROW_DATABASE_ID')

BASEROW_SKU_MAPPING_TABLE_ID = config('BASEROW_SKU_MAPPING_TABLE_ID')
BASEROW_INVENTORY_TABLE_ID = config('BASEROW_INVENTORY_TABLE_ID')
BASEROW_COMBO_TABLE_ID = config('BASEROW_COMBO_TABLE_ID')

# Airtable Configuration (using modern Personal Access Token)
AIRTABLE_BASE_ID = config('AIRTABLE_BASE_ID')
AIRTABLE_PERSONAL_ACCESS_TOKEN = config('AIRTABLE_PERSONAL_ACCESS_TOKEN')
AIRTABLE_WEBHOOK_SECRET = config('AIRTABLE_WEBHOOK_SECRET')

AIRTABLE_TABLES = {
    'sku_mappings': 'SKU_Mappings',
    'inventory': 'Inventory', 
    'combo_products': 'Combo_Products'
}

LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

GEMINI_API_KEY = config('GEMINI_API_KEY')


# Logging configuration with dynamic path
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': LOGS_DIR / 'airtable_sync.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO', 
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'core.airtable_sync': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
        'core.management.commands.sync_from_airtable': {
            'handlers': ['file', 'console'], 
            'level': 'INFO',
            'propagate': True,
        },
    },
}


# Security settings for SQL execution
SMART_ASSISTANT_MAX_ROWS = 1000  # Limit query results
SMART_ASSISTANT_TIMEOUT = 30     # Query timeout in seconds