# Generated by Django 5.2.3 on 2025-06-22 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('msku', models.CharField(help_text='Master SKU - unique product identifier', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('product_name', models.CharField(help_text='Product name from inventory data', max_length=255)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
                'ordering': ['msku'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('code', models.CharField(help_text='Warehouse code (TLCQ, BLR7, etc.)', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Human readable warehouse name', max_length=100)),
                ('location', models.CharField(help_text='City/region where warehouse is located', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warehouse',
                'verbose_name_plural': 'Warehouses',
                'db_table': 'warehouses',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField(default=0, help_text='Current available stock')),
                ('buffer_stock', models.IntegerField(default=0, help_text='Buffer/safety stock')),
                ('opening_stock', models.IntegerField(default=0, help_text='Opening stock for the period')),
                ('reorder_level', models.IntegerField(default=0, help_text='Reorder when stock hits this level')),
                ('max_stock_level', models.IntegerField(blank=True, help_text='Maximum stock capacity', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_stock_count_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='core.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='core.warehouse')),
            ],
            options={
                'verbose_name': 'Inventory Record',
                'verbose_name_plural': 'Inventory Records',
                'db_table': 'inventory',
                'ordering': ['product', 'warehouse'],
                'unique_together': {('product', 'warehouse')},
            },
        ),
    ]
