# Generated by Django 5.2.3 on 2025-06-22 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('code', models.CharField(choices=[('CSTE_AMAZON', 'CSTE Amazon'), ('CSTE_FK', 'CSTE Flipkart'), ('CSTE_MEESHO', 'CSTE Meesho'), ('GL_FK', 'GL Flipkart'), ('RUDRAV_MEESHO', 'Rudrav Meesho'), ('MISC', 'Miscellaneous')], help_text='Marketplace code (Panel)', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Human readable marketplace name', max_length=100)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission rate as percentage', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('api_endpoint', models.URLField(blank=True, null=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketplace',
                'verbose_name_plural': 'Marketplaces',
                'db_table': 'marketplaces',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SKUMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='Marketplace SKU identifier', max_length=100)),
                ('marketplace_product_url', models.URLField(blank=True, help_text='Product URL on marketplace', null=True)),
                ('marketplace_price', models.DecimalField(blank=True, decimal_places=2, help_text='Listed price on marketplace', max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True, help_text='Product image URL', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('PAUSED', 'Paused')], default='ACTIVE', help_text='Current listing status', max_length=20)),
                ('status_2', models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('IN_PROGRESS', 'In Progress'), ('BLOCKED', 'Blocked'), ('PAUSED', 'Paused')], help_text='Secondary status field', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.ForeignKey(help_text='Sales channel/panel', on_delete=django.db.models.deletion.CASCADE, related_name='sku_mappings', to='core.marketplace')),
                ('product', models.ForeignKey(help_text='Master product (MSKU)', on_delete=django.db.models.deletion.CASCADE, related_name='sku_mappings', to='core.product')),
            ],
            options={
                'verbose_name': 'SKU Mapping',
                'verbose_name_plural': 'SKU Mappings',
                'db_table': 'sku_mappings',
                'ordering': ['sku', 'marketplace'],
                'indexes': [models.Index(fields=['sku'], name='sku_mapping_sku_5b680b_idx'), models.Index(fields=['marketplace', 'status'], name='sku_mapping_marketp_0e090d_idx'), models.Index(fields=['product'], name='sku_mapping_product_3dac35_idx')],
                'unique_together': {('sku', 'marketplace')},
            },
        ),
    ]
