# Generated by Django 5.2.3 on 2025-06-22 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_marketplace_skumapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost price for margin calculations', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ComboProduct',
            fields=[
                ('combo_sku', models.CharField(help_text='Combo SKU identifier', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('combo_name', models.CharField(help_text='Display name for the combo', max_length=255)),
                ('combo_price', models.DecimalField(decimal_places=2, help_text='Selling price of complete combo', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_auto_split', models.BooleanField(default=True, help_text='Auto-split orders into individual items')),
                ('description', models.TextField(blank=True, help_text='Combo description for customers', null=True)),
                ('combo_image_url', models.URLField(blank=True, help_text='Main image for the combo', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marketplace', models.ForeignKey(help_text='Primary marketplace for this combo', on_delete=django.db.models.deletion.CASCADE, related_name='combo_products', to='core.marketplace')),
            ],
            options={
                'verbose_name': 'Combo Product',
                'verbose_name_plural': 'Combo Products',
                'db_table': 'combo_products',
                'ordering': ['combo_sku'],
            },
        ),
        migrations.CreateModel(
            name='ComboProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity of this product in the combo')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Display order within combo')),
                ('is_required', models.BooleanField(default=True, help_text='Is this item required in the combo')),
                ('item_note', models.CharField(blank=True, help_text='Special notes for this item', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('combo_product', models.ForeignKey(help_text='Parent combo product', on_delete=django.db.models.deletion.CASCADE, related_name='combo_items', to='core.comboproduct')),
                ('product', models.ForeignKey(help_text='Individual product in the combo', on_delete=django.db.models.deletion.CASCADE, related_name='combo_memberships', to='core.product')),
            ],
            options={
                'verbose_name': 'Combo Product Item',
                'verbose_name_plural': 'Combo Product Items',
                'db_table': 'combo_product_items',
                'ordering': ['sort_order', 'product__msku'],
            },
        ),
        migrations.AddIndex(
            model_name='comboproduct',
            index=models.Index(fields=['marketplace', 'is_active'], name='combo_produ_marketp_58e03a_idx'),
        ),
        migrations.AddIndex(
            model_name='comboproduct',
            index=models.Index(fields=['combo_sku'], name='combo_produ_combo_s_9c1880_idx'),
        ),
        migrations.AddIndex(
            model_name='comboproductitem',
            index=models.Index(fields=['combo_product'], name='combo_produ_combo_p_91cf25_idx'),
        ),
        migrations.AddIndex(
            model_name='comboproductitem',
            index=models.Index(fields=['product'], name='combo_produ_product_4109ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='comboproductitem',
            unique_together={('combo_product', 'product')},
        ),
    ]
