# Generated by Django 5.2.3 on 2025-06-22 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_product_cost_price_comboproduct_comboproductitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(help_text='Unique order identifier', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('order_type', models.CharField(choices=[('INBOUND', 'Inbound (Purchase/Restock)'), ('OUTBOUND', 'Outbound (Sale/Fulfillment)'), ('TRANSFER', 'Transfer (Between Warehouses)'), ('ADJUSTMENT', 'Inventory Adjustment'), ('RETURN', 'Return/Refund')], help_text='Type of order', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='PENDING', max_length=20)),
                ('order_date', models.DateTimeField(help_text='When the order was placed/created')),
                ('expected_delivery_date', models.DateTimeField(blank=True, help_text='Expected delivery/completion date', null=True)),
                ('actual_delivery_date', models.DateTimeField(blank=True, help_text='Actual delivery/completion date', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total order value', max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Shipping/handling cost', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Tax amount', max_digits=10)),
                ('external_order_id', models.CharField(blank=True, help_text='Marketplace/supplier order ID', max_length=100, null=True)),
                ('tracking_number', models.CharField(blank=True, help_text='Shipping tracking number', max_length=100, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('shipping_address', models.TextField(blank=True, help_text='Delivery address', null=True)),
                ('notes', models.TextField(blank=True, help_text='Internal notes about the order', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the order', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('marketplace', models.ForeignKey(blank=True, help_text='Source marketplace (for outbound orders)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.marketplace')),
                ('warehouse', models.ForeignKey(help_text='Primary warehouse for this order', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.warehouse')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity ordered')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Total for this line (quantity × unit_price)', max_digits=10)),
                ('item_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('RETURNED', 'Returned')], default='PENDING', help_text='Status of this specific item', max_length=20)),
                ('is_combo_item', models.BooleanField(default=False, help_text='True if this item is part of a combo')),
                ('parent_combo_sku', models.CharField(blank=True, help_text='Original combo SKU if this is a split item', max_length=100, null=True)),
                ('picked_quantity', models.PositiveIntegerField(default=0, help_text='Quantity actually picked')),
                ('shipped_quantity', models.PositiveIntegerField(default=0, help_text='Quantity shipped')),
                ('item_notes', models.TextField(blank=True, help_text='Notes specific to this line item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='Parent order', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.order')),
                ('product', models.ForeignKey(help_text='Product being ordered', on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
                'ordering': ['order', 'product__msku'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('movement_id', models.CharField(help_text='Unique movement tracking ID', max_length=100, primary_key=True, serialize=False, unique=True)),
                ('movement_type', models.CharField(choices=[('INBOUND', 'Stock In (Purchase/Restock)'), ('OUTBOUND', 'Stock Out (Sale/Fulfillment)'), ('TRANSFER_IN', 'Transfer In (From Another Warehouse)'), ('TRANSFER_OUT', 'Transfer Out (To Another Warehouse)'), ('ADJUSTMENT_POSITIVE', 'Positive Adjustment (Count Correction)'), ('ADJUSTMENT_NEGATIVE', 'Negative Adjustment (Count Correction)'), ('RETURN_IN', 'Return In (Customer Return)'), ('RETURN_OUT', 'Return Out (Supplier Return)'), ('DAMAGE', 'Damage/Loss'), ('COMBO_SPLIT', 'Combo Split (Combo → Individual Items)'), ('COMBO_COMBINE', 'Combo Combine (Individual Items → Combo)')], help_text='Type of inventory movement', max_length=30)),
                ('quantity', models.IntegerField(help_text='Quantity moved (positive or negative)')),
                ('stock_before', models.IntegerField(help_text='Stock level before movement')),
                ('stock_after', models.IntegerField(help_text='Stock level after movement')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit for this movement', max_digits=10, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Total cost for this movement', max_digits=12, null=True)),
                ('movement_date', models.DateTimeField(help_text='When the movement occurred')),
                ('reference_number', models.CharField(blank=True, help_text='External reference (invoice, receipt, etc.)', max_length=100, null=True)),
                ('reason', models.CharField(blank=True, help_text='Reason for the movement', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the movement', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who recorded the movement', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination_warehouse', models.ForeignKey(blank=True, help_text='Destination warehouse for transfers', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='core.warehouse')),
                ('product', models.ForeignKey(help_text='Product being moved', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='core.product')),
                ('warehouse', models.ForeignKey(help_text='Warehouse where movement occurred', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_movements', to='core.warehouse')),
                ('order', models.ForeignKey(blank=True, help_text='Related order (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='core.order')),
                ('order_item', models.ForeignKey(blank=True, help_text='Related order item (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='core.orderitem')),
            ],
            options={
                'verbose_name': 'Inventory Movement',
                'verbose_name_plural': 'Inventory Movements',
                'db_table': 'inventory_movements',
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_type', 'status'], name='orders_order_t_4558a7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['marketplace', 'order_date'], name='orders_marketp_73533c_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['warehouse', 'order_date'], name='orders_warehou_4c1bac_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_date'], name='orders_order_d_6e39a9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['external_order_id'], name='orders_externa_1cd7d5_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='order_items_order_i_26ad88_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='order_items_product_a53db1_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['is_combo_item'], name='order_items_is_comb_98140e_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['parent_combo_sku'], name='order_items_parent__0ec66b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['product', 'warehouse', 'movement_date'], name='inventory_m_product_9d9c69_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type', 'movement_date'], name='inventory_m_movemen_dd779a_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['order'], name='inventory_m_order_i_904320_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_date'], name='inventory_m_movemen_649272_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['reference_number'], name='inventory_m_referen_aef8d6_idx'),
        ),
    ]
