# Generated by Django 5.2.3 on 2025-06-22 01:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_orderitem_inventorymovement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorymovement',
            name='movement_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the movement occurred'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the order was placed/created'),
        ),
    ]
